### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'type'. Did you mean: 'astype'?

### ISSUE THREAD

**Issue by Hapluckyy** [ssbuild/aigc_evals#9]
您好！我在尝试运行您的测评程序时，在完成所有题目的测评后遇到了这个问题：
您有空的时候方便帮忙看一看吗

 python run_cmmlu.py

```
ld_religions
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 160/160 [00:52<00:00,  3.07it
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 67/67 [1:11:30<00:00, 64.03s/it]
```
```
]
Traceback (most recent call last):
  File "/home/edge2/aigc_evals/auto_eval/run_cmmlu.py", line 50, in <module>
    compute_match_metric(subjects,output_path,output_path_metric,data_type,MODEL)
  File "/home/edge2/aigc_evals/auto_eval/../auto_eval/mymetrics.py", line 28, in compute_match_metric
    for i, r in pd.json_normalize(events_df[events_df.type == "match"].data).iterrows():
                                            ^^^^^^^^^^^^^^
  File "/home/edge2/miniconda3/lib/python3.11/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'type'. Did you mean: 'astype'?

```

**Comment by ssbuild** [comment]
使用main 分支
